---
- hosts: "{{ HOSTS }}"
  gather_facts: no
  vars:
    service_name: undef

  tasks:
  - name: check service
    service_facts:

  - name: stop service
    service:
      name: "{{ service_name }}"
      state: stopped
    when: service_name + '.service' in services