---
- name: config management
  hosts: "{{ HOSTS | default('all') }}"
  become: yes
  vars:
    boinc_url: www.worldcommunitygrid.org

  tasks:
  - name: enable epel
    include_role:
      name: geerlingguy.repo-epel

  - name: configure password for ec2-user
    user:
      name: ec2-user
      password: '$6$rxiW8KZH$LUN.DuvVgMMzojJESXdD7ML8i40h.DHISO8vV0VfPmoJvzpNwil1OW26ZqvyZtyPOqmCDzr01CCJowCEoAaOI/'
    when: "'aws_ec2' in group_names"

  - name: deploy ssh keys
    authorized_key:
      user: root
      state: present
      key: "{{ ssh_public_key }}"
    when: ssh_public_key is defined

  - name: allow wheel group to sudo with NOPASSWD
    lineinfile:
      path: /etc/sudoers
      state: present
      regexp: '^%wheel ALL='
      line: '%wheel ALL=(ALL) NOPASSWD: ALL'
      validate: '/usr/sbin/visudo -cf %s'

  - name: install packages
    yum:
      name: 
        - at
        - 'boinc-client'
      state: latest

  - name: start services
    service:
      name: "{{ item }}"
      state: started
    loop:
      - 'boinc-client'
      - atd

  - name: World Community Grid
    command:
      cmd: "boinccmd --project_attach {{boinc_url}} {{boinc_auth}}"
      chdir: /var/lib/boinc/
      creates: "/var/lib/boinc/account_{{ boinc_url }}.xml"
    retries: 3
    delay: 5
    ignore_errors: true

  - name: stop boinc client
    service:
      name: boinc-client
      state: stopped
      enabled: false
