---
- hosts: "{{ HOSTS }}"
  become: yes
  collections:
    - willtome.insights

  tasks:
  - name: set hostname
    hostname:
      name: "{{ inventory_hostname }}"

  - name: remove rhui client packages
    yum:
      name: rh-amazon-rhui-client*
      state: removed

  - name: get current repos
    command:
      cmd: ls /etc/yum.repos.d/
    register: repos
    changed_when: False

  - name: remove existing rhui repos
    file:
      path: "/etc/yum.repos.d/{{ item }}"
      state: absent
    loop: "{{ repos.stdout_lines }}"
    when: "'rhui' in item"

  - name: register subscription mangler
    redhat_subscription:
      state: present
      activationkey: "{{ activation_key }}"
      org_id: "{{ org_id }}"

  - name: disable htb repo
    rhsm_repository:
      name: rhel-7-server-htb*
      state: disabled

  - name: configure Red Hat insights
    import_role:
      name: insights_client