---
- name: harden linux systems
  hosts: "{{ HOSTS | default('all') }}"
  become: yes

  tasks:
  - name: SSH Hardening
    include_role:
       name: dev-sec.ssh-hardening
    vars:
      sftp_enabled: true
  
  - name: Apply CIS Baseline
    include_role:
      name: mindpointgroup.rhel7-cis 
    vars:
      rhel7cis_rule_1_8: false #install updates
