---
- hosts: "{{ HOSTS }}"
  become: yes
  collections:
  - redhatinsights.insights

  tasks:
    - import_role:
        name: insights_client
      vars:
        insights_tags:
          env: prod
          site: chs
