---
- hosts: "{{ HOSTS }}"
  name: Install Monitoring Client
  become: yes
  vars:
    update_prometheus: true
  
  tasks:
  - name: add to monitor group
    add_host:
      name: "{{ inventory_hostname }}"
      groups: monitor

  - import_role:
      name: monitoring
      tasks_from: client

  - import_role:
      name: monitoring
      tasks_from: update_server
    delegate_to: monitoring
    
  - name: update CMDB
    servicenow.itsm.configuration_item:
      name: "{{ inventory_hostname }}"
      sys_class_name: cmdb_ci_server
      other:
        monitor: true
    delegate_to: localhost
    become: no

