---
- hosts: "{{ HOSTS }}"
  become: yes
  
  tasks:
  - name: add host to cmdb with ansible facts
    servicenow.itsm.configuration_item:
      name: "{{ ansible_hostname }}"
      mac_address: "{{ ansible_default_ipv4.macaddress }}"
      ip_address: "{{ ansible_default_ipv4.address }}"
      install_status: installed
      other:
        os_version: "{{ ansible_distribution_version }}"
        ram: "{{ ansible_memtotal_mb }}"
        cpu_count: "{{ ansible_processor_count }}"
        environment: "{{ env | default(omit) }}"
      sys_class_name: cmdb_ci_server
      sys_id: "{{ sys_id | default(omit) }}"
    delegate_to: localhost
    become: no
