---
plugin: amazon.aws.aws_ec2
regions:
  - us-east-1
filters:
  tag:Platform: linux
  key-name: wtome-lightbulb
hostnames:
  - tag:Name
compose:
  ansible_host: public_ip_address
keyed_groups:
  - key: placement.availability_zone
    prefix: aws
  - key: tags.Group
    separator: ""