---
- name: set hostname
  hostname:
    name: "{{ inventory_hostname | regex_replace('_','-')}}"
    
- name: install katello package
  yum:
    name: "https://{{ sat_url }}/pub/katello-ca-consumer-latest.noarch.rpm"
    state: present
    validate_certs: no
  when: sat_url is defined

- name: register subscription mangler
  redhat_subscription:
    state: present
    activationkey: "{{ activation_key }}"
    org_id: "{{ org_id }}"
    auto_attach: yes