---
- name: Get Job
  uri:
    url: "https://{{ tower_api_host }}/api/v2/jobs/{{ job_id | default(tower_current_job_id) }}/"
    method: GET
    validate_certs: "{{ tower_api_ssl }}"
    headers:
      Authorization: "Bearer {{tower_api_token}}"
      Content-Type: "application/json"
  register: job_out

- block:
  - name: Set Workflow ID
    set_fact: 
      workflow_id: "{{ job_out.json.summary_fields.source_workflow_job.id }}"
  
  - name: Get Workflow
    uri:
      url: "https://{{ tower_api_host }}/api/v2/workflow_jobs/{{ workflow_id }}"
      method: GET
      validate_certs: "{{ tower_api_ssl }}"
      headers:
        Authorization: "Bearer {{tower_api_token}}"
        Content-Type: "application/json"
    register: workflow_out

  - name: Get Workflow Nodes
    uri:
      url: "https://{{ tower_api_host }}/api/v2/workflow_jobs/{{ workflow_id }}/workflow_nodes"
      method: GET
      validate_certs: "{{ tower_api_ssl }}"
      headers:
        Authorization: "Bearer {{tower_api_token}}"
        Content-Type: "application/json"
    register: workflow_nodes_out

  - name: Set Workflow Nodes
    set_fact:
      workflow_nodes: "{{ workflow_nodes_out.json.results }}"

  when: job_out.json.launch_type == 'workflow'

